function init(self)
  msg.post("#collectionproxy", "load")
end

function update(self, dt)
  dtfixup.update(dt)
end

function on_message(self, message_id)
  if message_id == hash("proxy_loaded") then
    msg.post("#collectionproxy", "enable")
    dtfixup.init(function (factor)
      print("Adjusting time step with factor: " .. factor)
      msg.post("#collectionproxy", "set_time_step", { factor = factor, mode = 0 })
    end)
  end
end
